name: CI/CD Workflow

on:
  push:
    branches:
      - master  # Triggers on push to the master branch
  pull_request:
    branches:
      - master  # Triggers on pull request to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test

      - name: Build the app
        run: npm run build  # Adjust the command if necessary for your app

      # Deployment step (update this according to your deployment method)
      - name: Deploy to Production
        env:
          NODE_ENV: production
          # Add any environment variables required for deployment
          # for example: API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo "Deploying to production..."  # Replace this with actual deployment commands
          # Example command if deploying to a platform like Heroku:
          # npm run deploy  # Or whatever command is used to deploy your app
