name: CI/CD Workflow

on:
  push:
    branches:
      - master  # Triggers on push to the master branch
  pull_request:
    branches:
      - master  # Triggers on pull request to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify the Node.js version

      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test

      - name: Build the app
        env:  # Adding environment variables here
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
        run: npm run build  # Adjust the command if necessary for your app

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.3.10
        with:
          heroku_app_name: task-management-danny  # Replace with your Heroku app name
          heroku_email: ${{ secrets.HEROKU_EMAIL }}  # Your Heroku account email
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Heroku API key, stored in GitHub secrets
