name: Deploy React Frontend
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Install Dependencies
        run: |
          yarn global add cross-env react-app-rewired
          yarn install --legacy-peer-deps
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

      - name: Build React App
        run: yarn run build
        env:
          CI: false
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
