name: Deploy Task Management Frontend

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '2.7'  # node-gyp requires Python 2.7
        
      - name: Yarn Cache
        uses: c-hive/gha-yarn-cache@v1
        
      - name: Install node-gyp
        run: |
          npm config set python /usr/bin/python2.7
          npm install -g node-gyp@latest
        
      - name: Install dependencies
        run: |
          npm config set legacy-peer-deps true
          yarn install --frozen-lockfile
        
      - name: Build React App
        run: yarn build
        env:
          CI: false
          HTTPS: 'true'
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}
          PUBLIC_URL: ${{ secrets.PUBLIC_URL }}
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
